-- Helpers live in a schema the Data API does not expose.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

-- ---------------------------------------------------------------- tables
create table public.categories (
  id bigint generated by default as identity primary key,
  name varchar(120) not null check (length(trim(name)) > 0),
  name_pt varchar(120),
  name_tet varchar(120),
  display_order integer not null default 0
);

create table public.menu_items (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories (id) on delete cascade,
  name varchar(200) not null check (length(trim(name)) > 0),
  name_pt varchar(200),
  name_tet varchar(200),
  description text,
  description_pt text,
  description_tet text,
  price numeric(10, 2) not null default 0 check (price >= 0),
  image_url varchar(500),
  is_available boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index menu_items_category_id_idx on public.menu_items (category_id);

create table public.modifier_groups (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null references public.menu_items (id) on delete cascade,
  name varchar(120) not null check (length(trim(name)) > 0),
  selection_type varchar(20) not null default 'single' check (selection_type in ('single', 'multiple')),
  required boolean not null default false
);
create index modifier_groups_menu_item_id_idx on public.modifier_groups (menu_item_id);

create table public.modifier_options (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.modifier_groups (id) on delete cascade,
  name varchar(120) not null check (length(trim(name)) > 0),
  name_pt varchar(120),
  name_tet varchar(120),
  price_delta numeric(10, 2) not null default 0
);
create index modifier_options_group_id_idx on public.modifier_options (group_id);

create table public.promos (
  id bigint generated by default as identity primary key,
  image_url varchar(500) not null,
  caption text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Who may edit. Rows are added by hand (SQL editor), never from the API.
create table public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- helpers
create function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.admins where user_id = (select auth.uid()));
$$;
revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------- grants
revoke all on public.categories, public.menu_items, public.modifier_groups,
  public.modifier_options, public.promos, public.admins from anon, authenticated;
grant select on public.categories, public.menu_items, public.modifier_groups,
  public.modifier_options, public.promos to anon, authenticated;
grant insert, update, delete on public.categories, public.menu_items, public.modifier_groups,
  public.modifier_options, public.promos to authenticated;
grant select on public.admins to authenticated;
revoke all on all sequences in schema public from anon;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------- RLS
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.modifier_groups enable row level security;
alter table public.modifier_options enable row level security;
alter table public.promos enable row level security;
alter table public.admins enable row level security;

-- Menu: everyone reads, only admins write.
create policy "Menu categories are public" on public.categories
  for select to anon, authenticated using (true);
create policy "Admins insert categories" on public.categories
  for insert to authenticated with check ((select private.is_admin()));
create policy "Admins update categories" on public.categories
  for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy "Admins delete categories" on public.categories
  for delete to authenticated using ((select private.is_admin()));

create policy "Menu items are public" on public.menu_items
  for select to anon, authenticated using (true);
create policy "Admins insert menu items" on public.menu_items
  for insert to authenticated with check ((select private.is_admin()));
create policy "Admins update menu items" on public.menu_items
  for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy "Admins delete menu items" on public.menu_items
  for delete to authenticated using ((select private.is_admin()));

create policy "Modifier groups are public" on public.modifier_groups
  for select to anon, authenticated using (true);
create policy "Admins insert modifier groups" on public.modifier_groups
  for insert to authenticated with check ((select private.is_admin()));
create policy "Admins update modifier groups" on public.modifier_groups
  for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy "Admins delete modifier groups" on public.modifier_groups
  for delete to authenticated using ((select private.is_admin()));

create policy "Modifier options are public" on public.modifier_options
  for select to anon, authenticated using (true);
create policy "Admins insert modifier options" on public.modifier_options
  for insert to authenticated with check ((select private.is_admin()));
create policy "Admins update modifier options" on public.modifier_options
  for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy "Admins delete modifier options" on public.modifier_options
  for delete to authenticated using ((select private.is_admin()));

-- Promos: visitors see visible posters; admins see hidden ones too.
create policy "Visible promos are public" on public.promos
  for select to anon using (is_active);
create policy "Signed-in users see visible promos, admins see all" on public.promos
  for select to authenticated using (is_active or (select private.is_admin()));
create policy "Admins insert promos" on public.promos
  for insert to authenticated with check ((select private.is_admin()));
create policy "Admins update promos" on public.promos
  for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy "Admins delete promos" on public.promos
  for delete to authenticated using ((select private.is_admin()));

-- Lets the admin panel check whether the signed-in user is an admin.
create policy "Users can see their own admin row" on public.admins
  for select to authenticated using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------- save item
-- Creates (p_item_id null) or replaces an item together with its modifier
-- groups/options in one transaction. Runs as the caller, so RLS applies.
create function public.save_menu_item(p_item jsonb, p_item_id bigint default null)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_id bigint;
  v_group jsonb;
  v_group_id bigint;
begin
  if not (select private.is_admin()) then
    raise exception 'Only admins can edit the menu' using errcode = '42501';
  end if;

  if p_item_id is null then
    insert into public.menu_items (
      category_id, name, name_pt, name_tet, description, description_pt, description_tet,
      price, image_url, is_available, display_order
    ) values (
      (p_item->>'category_id')::bigint,
      p_item->>'name', p_item->>'name_pt', p_item->>'name_tet',
      p_item->>'description', p_item->>'description_pt', p_item->>'description_tet',
      coalesce((p_item->>'price')::numeric, 0),
      p_item->>'image_url',
      coalesce((p_item->>'is_available')::boolean, true),
      coalesce((p_item->>'display_order')::integer, 0)
    )
    returning id into v_id;
  else
    update public.menu_items set
      category_id = (p_item->>'category_id')::bigint,
      name = p_item->>'name',
      name_pt = p_item->>'name_pt',
      name_tet = p_item->>'name_tet',
      description = p_item->>'description',
      description_pt = p_item->>'description_pt',
      description_tet = p_item->>'description_tet',
      price = coalesce((p_item->>'price')::numeric, 0),
      image_url = p_item->>'image_url',
      is_available = coalesce((p_item->>'is_available')::boolean, true),
      display_order = coalesce((p_item->>'display_order')::integer, 0)
    where id = p_item_id
    returning id into v_id;

    if v_id is null then
      raise exception 'Menu item % not found', p_item_id using errcode = 'P0002';
    end if;

    delete from public.modifier_groups where menu_item_id = v_id;
  end if;

  for v_group in
    select g from jsonb_array_elements(coalesce(p_item->'modifier_groups', '[]'::jsonb)) as t(g)
  loop
    insert into public.modifier_groups (menu_item_id, name, selection_type, required)
    values (
      v_id,
      v_group->>'name',
      coalesce(v_group->>'selection_type', 'single'),
      coalesce((v_group->>'required')::boolean, false)
    )
    returning id into v_group_id;

    insert into public.modifier_options (group_id, name, name_pt, name_tet, price_delta)
    select v_group_id, o->>'name', o->>'name_pt', o->>'name_tet', coalesce((o->>'price_delta')::numeric, 0)
    from jsonb_array_elements(coalesce(v_group->'options', '[]'::jsonb)) with ordinality as t(o, ord)
    order by ord;
  end loop;

  return v_id;
end;
$$;
revoke all on function public.save_menu_item(jsonb, bigint) from public, anon;
grant execute on function public.save_menu_item(jsonb, bigint) to authenticated;
